---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v{{ .Chart.AppVersion }}/cert-manager.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1instance
        value: 2-cert-manager
    target:
      kind: CustomResourceDefinition
