---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v{{ .Chart.AppVersion }}/system-upgrade-controller.yaml
  - plans.yaml
