name: Updatecli

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,10,16,22 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
      - name: Run Updatecli in apply mode
        run: "updatecli compose apply"
        env:
          PAT: "${{ secrets.PAT }}"
          GH_USER: "${{ secrets.GH_USER }}"
